/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAttendanceNFT,
  IAttendanceNFTInterface,
} from "../../../contracts/AttendanceSynthesizer.sol/IAttendanceNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "tokenSessionIds",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAttendanceNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IAttendanceNFTInterface {
    return new Interface(_abi) as IAttendanceNFTInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAttendanceNFT {
    return new Contract(address, _abi, runner) as unknown as IAttendanceNFT;
  }
}
