/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AttendanceSynthesizer__factory } from "./AttendanceSynthesizer__factory";
export { IAttendanceNFT__factory } from "./IAttendanceNFT__factory";
