/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as attendanceNftSol from "./AttendanceNFT.sol";
export type { attendanceNftSol };
import type * as attendanceSynthesizerSol from "./AttendanceSynthesizer.sol";
export type { attendanceSynthesizerSol };
export type { AccessPassNFT } from "./AccessPassNFT";
export type { CertificateSBT } from "./CertificateSBT";
export type { RoleManager } from "./RoleManager";
export type { StudentPetNFT } from "./StudentPetNFT";
export type { StudentWorkNFT } from "./StudentWorkNFT";
