/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRoleManager,
  IRoleManagerInterface,
} from "../../../contracts/AttendanceNFT.sol/IRoleManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isTeacher",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRoleManager__factory {
  static readonly abi = _abi;
  static createInterface(): IRoleManagerInterface {
    return new Interface(_abi) as IRoleManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRoleManager {
    return new Contract(address, _abi, runner) as unknown as IRoleManager;
  }
}
