/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as attendanceNftSol from "./AttendanceNFT.sol";
export * as attendanceSynthesizerSol from "./AttendanceSynthesizer.sol";
export { AccessPassNFT__factory } from "./AccessPassNFT__factory";
export { CertificateSBT__factory } from "./CertificateSBT__factory";
export { RoleManager__factory } from "./RoleManager__factory";
export { StudentPetNFT__factory } from "./StudentPetNFT__factory";
export { StudentWorkNFT__factory } from "./StudentWorkNFT__factory";
