/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AttendanceSynthesizer } from "./AttendanceSynthesizer";
export type { IAttendanceNFT } from "./IAttendanceNFT";
